/* 
	DROP TABLE FACTURA
	DROP TABLE COMPRA
	DROP TABLE PC
	DROP TABLE CLIENTE
	DROP TABLE PLACA_VIDEO
	DROP TABLE MICROPROCESADOR
	DROP TABLE MEMORIA_RAM
	DROP TABLE PC
	DROP TABLE DISCO_RIGIDO
	DROP TABLE SUCURSAL
	DROP TABLE CIUDAD
	DROP TABLE ACCESORIO
	DROP TABLE REGISTRO_COMPRA_PC
*/
--[GD1C2021].[gd_esquema].[Maestra]

/* No esta en el DER. No lo agrego
CREATE TABLE COMPRA (
	COMPRA_NUMERO DECIMAL PRIMARY KEY,
	COMPRA_FECHA DATETIME2,
	COMPRA_CANTIDAD DECIMAL,
	COMPRA_PRECIO DECIMAL
)

*/

CREATE TABLE CLIENTE ( -- OK!
	ID_CLIENTE DECIMAL PRIMARY KEY,
	CLIENTE_APELLIDO NVARCHAR,
	CLIENTE_DIRECCION NVARCHAR,
	CLIENTE_DNI DECIMAL,
	CLIENTE_FECHA_NACIMIENTO DATETIME2,
	CLIENTE_MAIL NVARCHAR,
	CLIENTE_NOMBRE NVARCHAR,
	CLIENTE_TELEFONO DECIMAL
)
	
CREATE TABLE PLACA_VIDEO( -- OK!
	PLACA_VIDEO_CHIPSET NVARCHAR PRIMARY KEY,
	PLACA_VIDEO_CAPACIDAD NVARCHAR,
	PLACA_VIDEO_FABRICANTE NVARCHAR,
	PLACA_VIDEO_MODELO NVARCHAR,
	PLACA_VIDEO_VELOCIDAD DECIMAL
)

CREATE TABLE MICROPROCESADOR ( -- OK!!
	MICROPROCESADOR_CODIGO NVARCHAR PRIMARY KEY,
	MICROPROCESADOR_CACHE NVARCHAR,
	MICROPROCESADOR_CANT_HILOS DECIMAL,
	MICROPROCESADOR_FABRICANTE NVARCHAR,
	MICROPROCESADOR_VELOCIDAD NVARCHAR
)

CREATE TABLE MEMORIA_RAM ( -- OK!!
	MEMORIA_RAM_CODIGO NVARCHAR PRIMARY KEY,
	MEMORIA_RAM_CAPACIDAD NVARCHAR,
	MEMORIA_RAM_FABRICANTE NVARCHAR,
	MEMORIA_RAM_TIPO NVARCHAR,
	MEMORIA_RAM_VELOCIDAD NVARCHAR
)



CREATE TABLE DISCO_RIGIDO (  -- OK!!
	DISCO_RIGIDO_CODIGO NVARCHAR PRIMARY KEY,
	DISCO_RIGIDO_CAPACIDAD NVARCHAR,
	DISCO_RIGIDO_FABRICANTE NVARCHAR,
	DISCO_RIGIDO_TIPO NVARCHAR,
	DISCO_RIGIDO_VELOCIDAD NVARCHAR
)

CREATE TABLE SUCURSAL ( -- OK!
	SUCURSAL_ID DECIMAL PRIMARY KEY, --CREADA AUTOMATICAMENTE POR EL MOTOR
	CIUDAD NVARCHAR,
	SUCURSAL_DIR NVARCHAR,
	SUCURSAL_MAIL NVARCHAR,
	SUCURSAL_TEL DECIMAL
)

/*  NO SE INCLUYO EN EL DER, NO LO AGREGO.
CREATE TABLE CIUDAD (
	CIUDAD_ID DECIMAL PRIMARY KEY,
	CIUDAD NVARCHAR
)
*/


CREATE TABLE ACCESORIO( -- OK!
	ACCESORIO_CODIGO DECIMAL PRIMARY KEY,
	ACCESORIO_DESCRIPCION NVARCHAR
	)

CREATE TABLE PC ( -- OK!
	PC_CODIGO NVARCHAR PRIMARY KEY,
	-- NUMERO DE SERIE??'?
	PC_ANCHO DECIMAL,
	PC_ALTO DECIMAL,
	PC_PROFUNDIDAD DECIMAL,
	-- MODELO DEL GABINETE???? 
	DISCO_RIGIDO_CODIGO NVARCHAR FOREIGN KEY REFERENCES DISCO_RIGIDO(DISCO_RIGIDO_CODIGO),
	MEMORIA_RAM_CODIGO NVARCHAR FOREIGN KEY REFERENCES MEMORIA_RAM(MEMORIA_RAM_CODIGO),
	-- MOTHERBOARD????
	MICROPROCESADOR_CODIGO NVARCHAR FOREIGN KEY REFERENCES MICROPROCESADOR(MICROPROCESADOR_CODIGO),
	PLACA_VIDEO_CHIPSET NVARCHAR FOREIGN KEY REFERENCES PLACA_VIDEO(PLACA_VIDEO_CHIPSET)
)

-- Caso de uso tabla


CREATE TABLE COMPRA_PC(  -- OK!!
	COMPRA_NUMERO DECIMAL PRIMARY  KEY,
	ID_SUCURSAL DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	PC_CODIGO NVARCHAR FOREIGN KEY REFERENCES PC(PC_CODIGO),
	COMPRA_FECHA DATETIME2,
	COMPRA_PRECIO DATETIME2
)

CREATE TABLE COMPRA_ACCESORIO( -- OK!
	COMPRA_NUMERO DECIMAL PRIMARY KEY,
	ACCESORIO_CODIGO DECIMAL FOREIGN KEY REFERENCES ACCESORIO(ACCESORIO_CODIGO),
	ID_SUCURSAL DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	--FABRICANTE???????
	COMPRA_FECHA DATETIME2,
	COMPRA_PRECIO DECIMAL,
	COMPRA_CANTIDAD DECIMAL
)

CREATE TABLE VENTA_ACCESORIO ( -- OK!
	FACTURA_NUMERO DECIMAL PRIMARY KEY,
	FACTURA_FECHA DATETIME2,
	ID_SUCURSAL DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	ID_CLIENTE DECIMAL FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE)
)

CREATE TABLE VENTA_PC (  -- OK!
	FACTURA_NUMERO DECIMAL PRIMARY KEY,
	ID_SUCURSAL DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	PC_CODIGO NVARCHAR FOREIGN KEY REFERENCES PC(PC_CODIGO),
	ID_CLIENTE DECIMAL FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE),
	FACTURA_FECHA DATETIME2,
	PRECIO_VENTA DECIMAL
)

CREATE TABLE ACCESORIO_POR_VENTA ( -- OK!

	ID_ACCESORIOxVENTA DECIMAL PRIMARY KEY,
	ACCESORIO_CODIGO DECIMAL FOREIGN KEY REFERENCES ACCESORIO(ACCESORIO_CODIGO),
	FACTURA_NUMERO DECIMAL FOREIGN KEY REFERENCES VENTA_ACCESORIO(FACTURA_NUMERO),
	PRECIO_UNITARIO DECIMAL,
	VENTA_CANTIDAD DECIMAL
)

