/* 
	DROP TABLE FACTURA
	DROP TABLE COMPRA
	DROP TABLE PC
	DROP TABLE CLIENTE
	DROP TABLE PLACA_VIDEO
	DROP TABLE MICROPROCESADOR
	DROP TABLE MEMORIA_RAM
	DROP TABLE PC
	DROP TABLE DISCO_RIGIDO
	DROP TABLE SUCURSAL
	DROP TABLE CIUDAD
	DROP TABLE ACCESORIO
	DROP TABLE REGISTRO_COMPRA_PC
*/
--[GD1C2021].[gd_esquema].[Maestra]

CREATE TABLE COMPRA (
	COMPRA_NUMERO DECIMAL PRIMARY KEY,
	COMPRA_FECHA DATETIME2,
	COMPRA_CANTIDAD DECIMAL,
	COMPRA_PRECIO DECIMAL
)

CREATE TABLE CLIENTE (
	CLIENTE_NUMERO DECIMAL PRIMARY KEY,
	CLIENTE_APELLIDO NVARCHAR,
	CLIENTE_DIRECCION NVARCHAR,
	CLIENTE_DNI DECIMAL,
	CLIENTE_FECHA_NACIMIENTO DATETIME2,
	CLIENTE_MAIL NVARCHAR,
	CLIENTE_NOMBRE NVARCHAR,
	CLIENTE_TELEFONO DECIMAL
)
	
CREATE TABLE PLACA_VIDEO(
	PLACA_VIDEO_ID DECIMAL PRIMARY KEY,
	PLACA_VIDEO_CAPACIDAD NVARCHAR,
	PLACA_VIDEO_CHIPSET NVARCHAR,
	PLACA_VIDEO_FABRICANTE NVARCHAR,
	PLACA_VIDEO_MODELO NVARCHAR,
	PLACA_VIDEO_VELOCIDAD DECIMAL
)

CREATE TABLE MICROPROCESADOR (
	MICROPROCESADOR_ID DECIMAL PRIMARY KEY,
	MICROPROCESADOR_CACHE NVARCHAR,
	MICROPROCESADOR_CANT_HILOS DECIMAL,
	MICROPROCESADOR_CODIGO NVARCHAR,
	MICROPROCESADOR_FABRICANTE NVARCHAR,
	MICROPROCESADOR_VELOCIDAD NVARCHAR
)

CREATE TABLE MEMORIA_RAM (
	MEMORIA_RAM_ID DECIMAL PRIMARY KEY,
	MEMORIA_RAM_CAPACIDAD NVARCHAR,
	MEMORIA_RAM_CODIGO NVARCHAR,
	MEMORIA_RAM_FABRICANTE NVARCHAR,
	MEMORIA_RAM_TIPO NVARCHAR,
	MEMORIA_RAM_VELOCIDAD NVARCHAR
)



CREATE TABLE DISCO_RIGIDO (
	DISCO_RIGIDO_ID DECIMAL PRIMARY KEY,
	DISCO_RIGIDO_CAPACIDAD NVARCHAR,
	DISCO_RIGIDO_CODIGO NVARCHAR,
	DISCO_RIGIDO_FABRICANTE NVARCHAR,
	DISCO_RIGIDO_TIPO NVARCHAR,
	DISCO_RIGIDO_VELOCIDAD NVARCHAR
)

CREATE TABLE SUCURSAL (
	SUCURSAL_ID DECIMAL PRIMARY KEY,
	SUCURSAL_DIR NVARCHAR,
	SUCURSAL_MAIL NVARCHAR,
	SUCURSAL_TEL DECIMAL
)

CREATE TABLE CIUDAD (
	CIUDAD_ID DECIMAL PRIMARY KEY,
	CIUDAD NVARCHAR
)

CREATE TABLE ACCESORIO(
	ACCESORIO_CODIGO DECIMAL PRIMARY KEY,
	AC_DESCRIPCION NVARCHAR
	)

CREATE TABLE PC (
	PC_CODIGO NVARCHAR PRIMARY KEY,
	-- NUMERO DE SERIE??'?
	PC_ANCHO DECIMAL,
	PC_ALTO DECIMAL,
	PC_PROFUNDIDAD DECIMAL,
	-- MODELO DEL GABINETE???? 
	PC_DISCO_RIGIDO_ID DECIMAL FOREIGN KEY REFERENCES DISCO_RIGIDO(DISCO_RIGIDO_ID),
	PC_MEMORIA_RAM_ID DECIMAL FOREIGN KEY REFERENCES MEMORIA_RAM(MEMORIA_RAM_ID),
	-- MOTHERBOARD????
	PC_MICRORPROCESADOR_ID DECIMAL FOREIGN KEY REFERENCES MICROPROCESADOR(MICROPROCESADOR_ID),
	PC_PLACA_VIDEO_ID DECIMAL FOREIGN KEY REFERENCES PLACA_VIDEO(PLACA_VIDEO_ID)
)

-- Caso de uso tabla


CREATE TABLE REGISTRO_COMPRA_PC(
	REG_ID DECIMAL PRIMARY  KEY,
	REG_SUCURSAL_ID DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	REG_PC_CODIGO NVARCHAR FOREIGN KEY REFERENCES PC(PC_CODIGO),
	REG_DATOS_COMPRA_NUM DECIMAL FOREIGN KEY REFERENCES COMPRA(COMPRA_NUMERO) -- Me queda la duda de 'COMPRA_CANTIDAD'
)

CREATE TABLE REGISTRO_COMPRA_ACCESORIO(
	REG_ACCESORIO_CODIGO DECIMAL FOREIGN KEY REFERENCES ACCESORIO(ACCESORIO_CODIGO),
	REG_SUCURSAL_ID DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	--FABRICANTE???????
)

CREATE TABLE FACTURA_PC (
	FACTURA_NUMERO DECIMAL PRIMARY KEY,
	FACTURA_FECHA DATETIME2,
	FACTURA_REG_PC_ID DECIMAL FOREIGN KEY REFERENCES REGISTRO_COMPRA_PC(REG_ID),
	--SUCURSAL INCLUIDA EN FACTURA_REG_PC_ID, ES UN ERROR? PREFIERO NO REPETIR DATOS
	FACTURA_PRECIO_VENTA DECIMAL -- ES EL 20% DE LO QUE SE VENDIO LA PC. MEDIO RARO...
)

CREATE TABLE FACTURA_ACCESORIO (
	FACTURA_NUMERO DECIMAL PRIMARY KEY,
	FACTURA_FECHA DATETIME2,
	FACTURA_SUCURSAL_ID DECIMAL FOREIGN KEY REFERENCES SUCURSAL(SUCURSAL_ID),
	FACTURA_DETALLE_ACC decimal FOREIGN KEY REFERENCES ACCESORIO(ACCESORIO_CODIGO),
	-- No estoy muy seguro del FACTURA_DETALLE_ACC. Yo tengo que referenciar el detalle del accesorio
	FACTURA_PRECIO_VENTA DECIMAL,
	FACTURA_CANTIDAD DECIMAL
)

