

create procedure migrar_datos
as
begin
	-- MIGRAR ACCESORIOS
	INSERT INTO dbo.ACCESORIO (ACCESORIO_CODIGO, ACCESORIO_DESCRIPCION)
	SELECT DISTINCT ACCESORIO_CODIGO , AC_DESCRIPCION FROM gd_esquema.Maestra
	WHERE ACCESORIO_CODIGO IS NOT NULL AND AC_DESCRIPCION IS NOT NULL
	
	-- MIGRAR MICROPROCESADORES
	INSERT INTO GD1C2021.dbo.MICROPROCESADOR(MICROPROCESADOR_CODIGO,
											MICROPROCESADOR_CACHE,
											MICROPROCESADOR_CANT_HILOS,
											MICROPROCESADOR_FABRICANTE,
											MICROPROCESADOR_VELOCIDAD)
	SELECT DISTINCT
		MICROPROCESADOR_CODIGO,
		MICROPROCESADOR_CACHE ,
		MICROPROCESADOR_CANT_HILOS ,
		MICROPROCESADOR_FABRICANTE ,
		MICROPROCESADOR_VELOCIDAD 
	FROM gd_esquema.Maestra m
	WHERE MICROPROCESADOR_CODIGO IS NOT NULL AND 
		MICROPROCESADOR_CACHE IS NOT NULL AND
		MICROPROCESADOR_CANT_HILOS IS NOT NULL AND
		MICROPROCESADOR_FABRICANTE IS NOT NULL AND
		MICROPROCESADOR_VELOCIDAD IS NOT NULL
	
		-- MIGRAR MEMORIA RAM
		
	INSERT INTO DBO.MEMORIA_RAM (MEMORIA_RAM_CAPACIDAD,
								 MEMORIA_RAM_CODIGO,
								 MEMORIA_RAM_FABRICANTE,
								 MEMORIA_RAM_TIPO,
								 MEMORIA_RAM_VELOCIDAD)	
	SELECT DISTINCT
		MEMORIA_RAM_CAPACIDAD,
		MEMORIA_RAM_CODIGO,
		MEMORIA_RAM_FABRICANTE,
		MEMORIA_RAM_TIPO,
		MEMORIA_RAM_VELOCIDAD 
	FROM gd_esquema.Maestra m 
	WHERE MEMORIA_RAM_CAPACIDAD IS NOT NULL AND 
		MEMORIA_RAM_CODIGO IS NOT NULL AND
		MEMORIA_RAM_FABRICANTE IS NOT NULL AND
		MEMORIA_RAM_TIPO IS NOT NULL AND
		MEMORIA_RAM_VELOCIDAD IS NOT NULL
		
	-- MIGRAR PLACA VIDEO
	
	INSERT INTO dbo.PLACA_VIDEO(PLACA_VIDEO_CAPACIDAD, 
								PLACA_VIDEO_CHIPSET,
								PLACA_VIDEO_FABRICANTE,
								PLACA_VIDEO_MODELO,
								PLACA_VIDEO_VELOCIDAD )
	SELECT DISTINCT 
		PLACA_VIDEO_CAPACIDAD ,
		PLACA_VIDEO_CHIPSET ,
		PLACA_VIDEO_FABRICANTE,
		PLACA_VIDEO_MODELO,
		PLACA_VIDEO_VELOCIDAD 
	FROM gd_esquema.Maestra m
	WHERE PLACA_VIDEO_CAPACIDAD IS NOT NULL AND 
		PLACA_VIDEO_CHIPSET IS NOT NULL AND
		PLACA_VIDEO_FABRICANTE IS NOT NULL AND
		PLACA_VIDEO_MODELO IS NOT NULL AND
		PLACA_VIDEO_VELOCIDAD IS NOT NULL
	
	-- MIGRAR DISCO DURO
	
	INSERT INTO dbo.DISCO_RIGIDO(DISCO_RIGIDO_CAPACIDAD,
								 DISCO_RIGIDO_CODIGO,
								 DISCO_RIGIDO_FABRICANTE,
								 DISCO_RIGIDO_TIPO,
								 DISCO_RIGIDO_VELOCIDAD)
	SELECT DISTINCT
		DISCO_RIGIDO_CAPACIDAD ,
		DISCO_RIGIDO_CODIGO ,
		DISCO_RIGIDO_FABRICANTE ,
		DISCO_RIGIDO_TIPO ,
		DISCO_RIGIDO_VELOCIDAD 
	FROM gd_esquema.Maestra m 
		WHERE DISCO_RIGIDO_CAPACIDAD IS NOT NULL AND 
			  DISCO_RIGIDO_CODIGO  IS NOT NULL AND 
			  DISCO_RIGIDO_FABRICANTE IS NOT NULL AND 
			  DISCO_RIGIDO_TIPO IS NOT NULL AND 
			  DISCO_RIGIDO_VELOCIDAD IS NOT NULL 
			 
	-- MIGRAR PC
	INSERT INTO dbo.PC(DISCO_RIGIDO_CODIGO,
					   MEMORIA_RAM_CODIGO,
					   MICROPROCESADOR_CODIGO,
					   PLACA_VIDEO_CHIPSET,
					   PC_ALTO,
					   PC_ANCHO,
					   PC_CODIGO)
	SELECT DISTINCT 
		DISCO_RIGIDO_CODIGO,
		MEMORIA_RAM_CODIGO, 
		MICROPROCESADOR_CODIGO, --NVARCHAR(50)
		PLACA_VIDEO_CHIPSET, -- Podria ser el modelo NVARCHAR(50)
		PC_ALTO,
		PC_ANCHO,
		PC_CODIGO 
	FROM gd_esquema.Maestra m 
	WHERE DISCO_RIGIDO_CODIGO IS NOT NULL AND
		 MEMORIA_RAM_CODIGO IS NOT NULL AND 
		 MICROPROCESADOR_CODIGO IS NOT NULL AND 
		 PLACA_VIDEO_CHIPSET IS NOT NULL AND 
		 PC_ALTO IS NOT NULL AND
		 PC_ANCHO IS NOT NULL AND 
		 PC_CODIGO IS NOT NULL 
			  
			  
end



/*
alter table dbo.PLACA_VIDEO 
alter column PLACA_VIDEO_velocidad NVARCHAR(255);

alter table dbo.PC
alter column PC_CODIGO NVARCHAR(255) NOT NULL;


ALTER TABLE dbo.COMPRA_PC
ALTER COLUMN  PC_CODIGO NVARCHAR(255);

ALTER TABLE dbo.PC 
ALTER COLUMN PC_CODIGO DECIMAL NOT NULL;

ALTER TABLE DBO.VENTA_PC 
ALTER COLUMN PC_CODIGO NVARCHAR(255);

ALTER TABLE dbo.COMPRA_PC 
ADD FOREIGN KEY(PC_CODIGO) REFERENCES PC(PC_CODIGO);


ALTER TABLE DBO.COMPRA_PC 
DROP COLUMN PC_CODIGO ;

ALTER TABLE DBO.COMPRA_PC 
DROP CONSTRAINT FK__COMPRA_PC__PC_CO__4CA06362 ;

ALTER TABLE DBO.VENTA_PC  
DROP CONSTRAINT FK__VENTA_PC__PC_COD__4E88ABD4;

ALTER TABLE DBO.PC
DROP CONSTRAINT PK__PC__A1C82F9A74AFB743;

alter table dbo.PC 
ADD PRIMARY KEY(PC_CODIGO)

ALTER TABLE DBO.COMPRA_PC 


*/

exec migrar_datos 

/* 
	begin transaction


	rollback transaction

*/

/*
	DELETE FROM dbo.ACCESORIO
	DELETE FROM dbo.MICROPROCESADOR
	DELETE FROM dbo.MEMORIA_RAM
	DELETE FROM dbo.PLACA_VIDEO
	DELETE FROM dbo.DISCO_RIGIDO
	
	
	
	
	
	
	
	
*/