

create procedure migrar_datos
as
begin
	
	/*
	 * HACER TRUNCATE DE TODAS LAS TABLAS
	 * 
	 */
	
	
	-- MIGRAR ACCESORIOS
	INSERT INTO dbo.ACCESORIO (ACCESORIO_CODIGO, ACCESORIO_DESCRIPCION)
	SELECT DISTINCT ACCESORIO_CODIGO , AC_DESCRIPCION FROM gd_esquema.Maestra
	WHERE ACCESORIO_CODIGO IS NOT NULL AND AC_DESCRIPCION IS NOT NULL
	
	-- MIGRAR MICROPROCESADORES
	INSERT INTO GD1C2021.dbo.MICROPROCESADOR(MICROPROCESADOR_CODIGO,
											MICROPROCESADOR_CACHE,
											MICROPROCESADOR_CANT_HILOS,
											MICROPROCESADOR_FABRICANTE,
											MICROPROCESADOR_VELOCIDAD)
	SELECT DISTINCT
		MICROPROCESADOR_CODIGO,
		MICROPROCESADOR_CACHE ,
		MICROPROCESADOR_CANT_HILOS ,
		MICROPROCESADOR_FABRICANTE ,
		MICROPROCESADOR_VELOCIDAD 
	FROM gd_esquema.Maestra m
	WHERE MICROPROCESADOR_CODIGO IS NOT NULL AND 
		MICROPROCESADOR_CACHE IS NOT NULL AND
		MICROPROCESADOR_CANT_HILOS IS NOT NULL AND
		MICROPROCESADOR_FABRICANTE IS NOT NULL AND
		MICROPROCESADOR_VELOCIDAD IS NOT NULL
	
		-- MIGRAR MEMORIA RAM
		
	INSERT INTO DBO.MEMORIA_RAM (MEMORIA_RAM_CAPACIDAD,
								 MEMORIA_RAM_CODIGO,
								 MEMORIA_RAM_FABRICANTE,
								 MEMORIA_RAM_TIPO,
								 MEMORIA_RAM_VELOCIDAD)	
	SELECT DISTINCT
		MEMORIA_RAM_CAPACIDAD,
		MEMORIA_RAM_CODIGO,
		MEMORIA_RAM_FABRICANTE,
		MEMORIA_RAM_TIPO,
		MEMORIA_RAM_VELOCIDAD 
	FROM gd_esquema.Maestra m 
	WHERE MEMORIA_RAM_CAPACIDAD IS NOT NULL AND 
		MEMORIA_RAM_CODIGO IS NOT NULL AND
		MEMORIA_RAM_FABRICANTE IS NOT NULL AND
		MEMORIA_RAM_TIPO IS NOT NULL AND
		MEMORIA_RAM_VELOCIDAD IS NOT NULL
		
	-- MIGRAR PLACA VIDEO
	
	INSERT INTO dbo.PLACA_VIDEO(PLACA_VIDEO_CAPACIDAD, 
								PLACA_VIDEO_CHIPSET,
								PLACA_VIDEO_FABRICANTE,
								PLACA_VIDEO_MODELO,
								PLACA_VIDEO_VELOCIDAD )
	SELECT DISTINCT 
		PLACA_VIDEO_CAPACIDAD ,
		PLACA_VIDEO_CHIPSET ,
		PLACA_VIDEO_FABRICANTE,
		PLACA_VIDEO_MODELO,
		PLACA_VIDEO_VELOCIDAD 
	FROM gd_esquema.Maestra m
	WHERE PLACA_VIDEO_CAPACIDAD IS NOT NULL AND 
		PLACA_VIDEO_CHIPSET IS NOT NULL AND
		PLACA_VIDEO_FABRICANTE IS NOT NULL AND
		PLACA_VIDEO_MODELO IS NOT NULL AND
		PLACA_VIDEO_VELOCIDAD IS NOT NULL
	
	-- MIGRAR DISCO DURO
	
	INSERT INTO dbo.DISCO_RIGIDO(DISCO_RIGIDO_CAPACIDAD,
								 DISCO_RIGIDO_CODIGO,
								 DISCO_RIGIDO_FABRICANTE,
								 DISCO_RIGIDO_TIPO,
								 DISCO_RIGIDO_VELOCIDAD)
	SELECT DISTINCT
		DISCO_RIGIDO_CAPACIDAD ,
		DISCO_RIGIDO_CODIGO ,
		DISCO_RIGIDO_FABRICANTE ,
		DISCO_RIGIDO_TIPO ,
		DISCO_RIGIDO_VELOCIDAD 
	FROM gd_esquema.Maestra m 
		WHERE DISCO_RIGIDO_CAPACIDAD IS NOT NULL AND 
			  DISCO_RIGIDO_CODIGO  IS NOT NULL AND 
			  DISCO_RIGIDO_FABRICANTE IS NOT NULL AND 
			  DISCO_RIGIDO_TIPO IS NOT NULL AND 
			  DISCO_RIGIDO_VELOCIDAD IS NOT NULL 
			 
	-- MIGRAR PC
	

	INSERT INTO dbo.PC(DISCO_RIGIDO_CODIGO,
	   MEMORIA_RAM_CODIGO,
	   MICROPROCESADOR_CODIGO,
	   PLACA_VIDEO_CHIPSET,
	   PC_ALTO,
	   PC_ANCHO,
	   PC_CODIGO)
	SELECT DISTINCT 
		DISCO_RIGIDO_CODIGO,
		MEMORIA_RAM_CODIGO, 
		MICROPROCESADOR_CODIGO, --NVARCHAR(50)
		PLACA_VIDEO_CHIPSET, -- Podria ser el modelo NVARCHAR(50)
		PC_ALTO,
		PC_ANCHO,
		PC_CODIGO 
	FROM gd_esquema.Maestra m 
	WHERE DISCO_RIGIDO_CODIGO IS NOT NULL AND
		 MEMORIA_RAM_CODIGO IS NOT NULL AND 
		 MICROPROCESADOR_CODIGO IS NOT NULL AND 
		 PLACA_VIDEO_CHIPSET IS NOT NULL AND 
		 PC_ALTO IS NOT NULL AND
		 PC_ANCHO IS NOT NULL AND 
		 PC_CODIGO IS NOT NULL 
	
	-- MIGRAR SUCURSAL (NO INCLUYO CIUDAD YA QUE NO SE DA INFO RESPECTO A ESO)
	
	INSERT INTO dbo.SUCURSAL (SUCURSAL_ID,
							  SUCURSAL_DIR,
							  SUCURSAL_MAIL,
							  SUCURSAL_TEL,
							  CIUDAD)
	 SELECT DISTINCT
		ROW_NUMBER() OVER ( ORDER BY SUCURSAL_DIR), -- Estoy creando una PK ya que la tabla maestra no trae.
		SUCURSAL_DIR,
		SUCURSAL_MAIL,
		SUCURSAL_TEL,
		CIUDAD
	FROM GD1C2021.gd_esquema.Maestra m 
	GROUP BY SUCURSAL_DIR, SUCURSAL_MAIL, SUCURSAL_TEL, CIUDAD
			
	-- MIGRA COMPRA_PC
	
	INSERT INTO DBO.COMPRA_PC(COMPRA_NUMERO,
							  PC_CODIGO,
							  COMPRA_FECHA,
							  COMPRA_PRECIO,
							  ID_SUCURSAL)
	SELECT DISTINCT 
		COMPRA_NUMERO,
		PC_CODIGO,
		COMPRA_FECHA,
		COMPRA_PRECIO,
		( SELECT s.SUCURSAL_ID FROM GD1C2021.dbo.SUCURSAL s
		  WHERE s.SUCURSAL_DIR = m.SUCURSAL_DIR AND
		  	   s.SUCURSAL_MAIL = m.SUCURSAL_MAIL AND
		  	   s.SUCURSAL_TEL = m.SUCURSAL_TEL) AS SUCURSAL_ID
	FROM GD1C2021.gd_esquema.Maestra m
	WHERE COMPRA_NUMERO IS NOT NULL AND 
		  PC_CODIGO IS NOT NULL AND 
		  COMPRA_FECHA IS NOT NULL AND 
		  COMPRA_PRECIO IS NOT NULL  -- SE PODRIA TAMB FILTRAR LOS NULL EN SUCURSAL PERO BUE
	
	-- MIGRA CLIENTE
	
	INSERT INTO GD1C2021.dbo.CLIENTE(ID_CLIENTE,
									 CLIENTE_DNI,
									 CLIENTE_APELLIDO,
									 CLIENTE_NOMBRE,
									 CLIENTE_DIRECCION,
									 CLIENTE_FECHA_NACIMIENTO,
									 CLIENTE_MAIL,
									 CLIENTE_TELEFONO)
		SELECT DISTINCT
		ROW_NUMBER() OVER ( ORDER BY CLIENTE_DNI,
							CLIENTE_APELLIDO,
							CLIENTE_NOMBRE), -- Estoy creando una PK ya que la tabla maestra no trae.
		CLIENTE_DNI ,
		CLIENTE_APELLIDO,
		CLIENTE_NOMBRE ,
		CLIENTE_DIRECCION,
		CLIENTE_FECHA_NACIMIENTO ,
		CLIENTE_MAIL ,
		CLIENTE_TELEFONO 
	FROM GD1C2021.gd_esquema.Maestra m
	WHERE CLIENTE_DNI IS NOT NULL AND 
		  CLIENTE_APELLIDO IS NOT NULL AND 
		  CLIENTE_NOMBRE IS NOT NULL AND
		  CLIENTE_DIRECCION IS NOT NULL AND 
		  CLIENTE_FECHA_NACIMIENTO IS NOT NULL AND 
		  CLIENTE_MAIL IS NOT NULL AND 
		  CLIENTE_TELEFONO IS NOT NULL

		  
		  
		  
	
	-- CREAR TABLA TEMPORAL PRECIO_PRODUCTO_PC
	
	CREATE TABLE GD1C2021.dbo.#PRECIO_PRODUCTO_PC(
	PC_CODIGO NVARCHAR(255),
	COMPRA_PRECIO DECIMAL
	)	  
		  
	INSERT INTO GD1C2021.dbo.#PRECIO_PRODUCTO_PC
	Select DISTINCT
		m.PC_CODIGO,
		m.COMPRA_PRECIO
	from gd_esquema.Maestra m 
	WHERE m.pc_codigo is not null and ISNULL(m.CLIENTE_DNI,0) = 0 
		  
	-- MIGRA VENTA_PC

	INSERT INTO dbo.VENTA_PC(FACTURA_NUMERO,
							 FACTURA_FECHA,
							 PC_CODIGO,
							 ID_SUCURSAL,
							 ID_CLIENTE, 
							 PRECIO_VENTA)
	SELECT 
	m.FACTURA_NUMERO,
	m.FACTURA_FECHA,
	m.PC_CODIGO,
	s.SUCURSAL_ID,
	c.ID_CLIENTE,
	pp.COMPRA_PRECIO * 0.2 AS PRECIO_VENTA
	from gd_esquema.Maestra m 
	JOIN dbo.SUCURSAL s
	ON s.SUCURSAL_DIR = m.SUCURSAL_DIR AND
    s.SUCURSAL_MAIL = m.SUCURSAL_MAIL AND
   	s.SUCURSAL_TEL = m.SUCURSAL_TEL
	JOIN dbo.CLIENTE c 
	ON c.CLIENTE_APELLIDO = m.CLIENTE_APELLIDO AND 
   	c.CLIENTE_DIRECCION = m.CLIENTE_DIRECCION AND 
   	c.CLIENTE_DNI = m.CLIENTE_DNI AND 
  	c.CLIENTE_FECHA_NACIMIENTO = m.CLIENTE_FECHA_NACIMIENTO AND 
   	c.CLIENTE_MAIL = m.CLIENTE_MAIL AND 
   	c.CLIENTE_NOMBRE = m.CLIENTE_NOMBRE AND 
   	c.CLIENTE_TELEFONO = m.CLIENTE_TELEFONO
	JOIN #PRECIO_PRODUCTO_PC pp
	ON pp.PC_CODIGO = m.PC_CODIGO
	WHERE m.FACTURA_NUMERO IS NOT NULL AND 
	      m.FACTURA_FECHA IS NOT NULL AND
	  	  m.PC_CODIGO IS NOT NULL AND 
	  	  s.SUCURSAL_ID IS NOT NULL AND 
	  	  c.ID_CLIENTE IS NOT NULL AND
	  	  ISNULL(m.CLIENTE_DNI,0) > 0

	-- MIGRA ACCESORIO
	
	


end



/*
alter table dbo.PLACA_VIDEO 
alter column PLACA_VIDEO_velocidad NVARCHAR(255);

alter table dbo.PC
alter column PC_CODIGO NVARCHAR(255) NOT NULL;


ALTER TABLE dbo.COMPRA_PC
ALTER COLUMN  PC_CODIGO NVARCHAR(255);

ALTER TABLE dbo.PC 
ALTER COLUMN PC_CODIGO DECIMAL NOT NULL;

ALTER TABLE DBO.VENTA_PC 
ALTER COLUMN PC_CODIGO NVARCHAR(255);

ALTER TABLE dbo.COMPRA_PC 
ADD FOREIGN KEY(PC_CODIGO) REFERENCES PC(PC_CODIGO);


ALTER TABLE DBO.COMPRA_PC 
DROP COLUMN PC_CODIGO ;

ALTER TABLE DBO.COMPRA_PC 
DROP CONSTRAINT FK__COMPRA_PC__PC_CO__4CA06362 ;

ALTER TABLE DBO.VENTA_PC  
DROP CONSTRAINT FK__VENTA_PC__PC_COD__4E88ABD4;

ALTER TABLE DBO.PC
DROP CONSTRAINT PK__PC__A1C82F9A74AFB743;

alter table dbo.PC 
ADD PRIMARY KEY(PC_CODIGO)

ALTER TABLE DBO.COMPRA_PC 


*/

exec migrar_datos 

/* 
	begin transaction


	rollback transaction

*/

/*
	DELETE FROM dbo.ACCESORIO
	DELETE FROM dbo.MICROPROCESADOR
	DELETE FROM dbo.MEMORIA_RAM
	DELETE FROM dbo.PLACA_VIDEO
	DELETE FROM dbo.DISCO_RIGIDO
	DELETE FROM dbo.COMPRA_PC
	DELETE FROM dbo.SUCURSAL
	DELETE FROM dbo.CLIENTE
	
	
	
	
	
	
*/
